spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/hbipm-plus?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      stat-view-servlet:
        login-username: admin
        login-password: admin
